server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

spring.security.oauth2.resourceserver.jwt:
  jwk-set-uri: http://localhost:9999/does-not-exist

app:
  security:
    disableAuth: false
  downstream:
    accountsBaseUrl: https://accounts-service-whreljigvq-ey.a.run.app
    tradingBaseUrl: https://trading-service-whreljigvq-ey.a.run.app

spring:
  cloud:
    gateway:
      routes:
        - id: root
          uri: no://op
          predicates:
            - Path=/
          filters:
            - RedirectTo=302,/actuator/health
        - id: accounts-actuator
          uri: ${app.downstream.accountsBaseUrl}
          predicates:
            - Path=/accounts/actuator/**
          filters:
            - RewritePath=/accounts/(?<segment>.*),/${segment}
        - id: accounts-service
          uri: ${app.downstream.accountsBaseUrl}
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/accounts/(?<segment>.*),/v1/${segment}
        - id: trading-actuator
          uri: ${app.downstream.tradingBaseUrl}
          predicates:
            - Path=/trading/actuator/**
          filters:
            - RewritePath=/trading/(?<segment>.*),/${segment}
        - id: trading-service
          uri: ${app.downstream.tradingBaseUrl}
          predicates:
            - Path=/trading/**
          filters:
            - RewritePath=/trading/(?<segment>.*),/v1/${segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
